spring:
  application:
    name: notification-service

server:
  port: 8082
  servlet:
    context-path: /notification

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
