spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/community/**
        - id: sentiment-service
          uri: lb://sentiment-service
          predicates:
            - Path=/sentiment/**
        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/subscription/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8086
