spring:
  application:
    name: subscribe-service

server:
  port: 8084
  servlet:
    context-path: /subscription

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
