spring:
  application:
    name: community-service

server:
  port: 8085
  servlet:
    context-path: /community

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
