# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Virtual Health Consultant

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permissions for gradlew files
        run: |
          chmod +x community-service/gradlew
          chmod +x notification-service/gradlew
          chmod +x sentiment-analysis-service/gradlew
          chmod +x subscription-service/gradlew
          chmod +x user-service/gradlew

      # Build community-service
      - name: Build community-service
        run: cd community-service && ./gradlew build -x test

      # Build notification-service
      - name: Build notification-service
        run: cd notification-service && ./gradlew build -x test

      # Build sentiment-analysis-service
      - name: Build sentiment-analysis-service
        run: cd sentiment-analysis-service && ./gradlew build -x test

      # Build subscription-service
      - name: Build subscription-service
        run: cd subscription-service && ./gradlew build -x test

      # Build user-service
      - name: Build user-service
        run: cd user-service && ./gradlew build -x test
